### ISSUE TITLE
Build failing for micro:bit

### ISSUE THREAD

**Issue by microbit-mark** [xinabox/pxt-CW01#2]
HI @gotfredsen @KalbeAbbas 

This extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

 microsoft/pxt-microbit#3506 provides more information on approved builds that are failing.

Whilst it is not on our approved list, we have had a user get in contact to say that it is not working for them.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, people attempting to use your extension with a micro:bit V2 board will get error 929.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

**Comment by KalbeAbbas** [comment]
Hi. Thanks for the info. We are working on our extensions to solve this issue for microbit v2. But, we are also having issue with microbit V1 on online editor. It hangs on compiling screen and takes forever.

To replicate please try this project:
https://makecode.microbit.org/_UzeHdHYhHAyh

Many thanks.

**Comment by KalbeAbbas** [comment]
Made to work with old microbit
